// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// coaltimes
Rcpp::NumericVector coaltimes(int n, int population_type, double kappa, int Ne0, int T, int NeT, double beta, Rcpp::NumericVector tk, Rcpp::NumericVector eta);
RcppExport SEXP _SNPfreq_coaltimes(SEXP nSEXP, SEXP population_typeSEXP, SEXP kappaSEXP, SEXP Ne0SEXP, SEXP TSEXP, SEXP NeTSEXP, SEXP betaSEXP, SEXP tkSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type population_type(population_typeSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type Ne0(Ne0SEXP);
    Rcpp::traits::input_parameter< int >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type NeT(NeTSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type tk(tkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(coaltimes(n, population_type, kappa, Ne0, T, NeT, beta, tk, eta));
    return rcpp_result_gen;
END_RCPP
}
// SNPprob
Rcpp::NumericVector SNPprob(int n, Rcpp::IntegerVector b, Rcpp::NumericVector e);
RcppExport SEXP _SNPfreq_SNPprob(SEXP nSEXP, SEXP bSEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPprob(n, b, e));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SNPfreq_coaltimes", (DL_FUNC) &_SNPfreq_coaltimes, 9},
    {"_SNPfreq_SNPprob", (DL_FUNC) &_SNPfreq_SNPprob, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SNPfreq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
