# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname coaltimes
#' @export
coaltimes <- function(n, population_type = 0L, kappa = 1.0, Ne0 = 100L, T = 10L, NeT = 10L, beta = 0.5, tk = as.numeric( c()), eta = as.numeric( c())) {
    .Call(`_SNPprob_coaltimes`, n, population_type, kappa, Ne0, T, NeT, beta, tk, eta)
}

#' @rdname SNPprob
#' @export
SNPprob <- function(n, b, e) {
    .Call(`_SNPprob_SNPprob`, n, b, e)
}

